// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK97CQB94PBuIWjmnV_FJuBny2P37VS3k',
    appId: '1:881105391516:web:24a1a83257ce81736d8259',
    messagingSenderId: '881105391516',
    projectId: 'fir-eb1b0',
    authDomain: 'fir-eb1b0.firebaseapp.com',
    storageBucket: 'fir-eb1b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6mYUh6c6-V68XApIdE-_YiOKPneHiW4',
    appId: '1:881105391516:android:5536694b1971fa026d8259',
    messagingSenderId: '881105391516',
    projectId: 'fir-eb1b0',
    storageBucket: 'fir-eb1b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybDLPzUHCpyk0ueqEwnyiXNzyvE0UNwI',
    appId: '1:881105391516:ios:27e3ad1de30196906d8259',
    messagingSenderId: '881105391516',
    projectId: 'fir-eb1b0',
    storageBucket: 'fir-eb1b0.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybDLPzUHCpyk0ueqEwnyiXNzyvE0UNwI',
    appId: '1:881105391516:ios:49e58db436a377e36d8259',
    messagingSenderId: '881105391516',
    projectId: 'fir-eb1b0',
    storageBucket: 'fir-eb1b0.appspot.com',
    iosBundleId: 'com.example.amazonClone.RunnerTests',
  );
}
